package me.ifmo.backend.entities.enums;

public enum NotificationType {
    ACCOUNT_ACTIVATION,
    PASSWORD_RECOVERY,
    ACCOUNT_STATUS_CHANGED,

    RESERVATION_CREATED,
    RESERVATION_READY,
    RESERVATION_CANCELLED,
    RESERVATION_EXPIRED,

    LOAN_CREATED,
    LOAN_DUE_SOON,
    LOAN_OVERDUE,
    LOAN_RETURNED,
    LOAN_RENEWED,
    LOAN_RENEWAL_REJECTED,

    FINE_CREATED,
    FINE_PAID,
    FINE_CANCELLED,
    FINE_MANUALLY_CLEARED,

    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_WARNING_CREATED,

    SYSTEM_MESSAGE
}
