package me.ifmo.backend.entities.enums;

public enum NotificationType {
    ACCOUNT_ACTIVATION,
    PASSWORD_RECOVERY,
    ACCOUNT_STATUS_CHANGED,

    RESERVATION_CREATED,
    RESERVATION_READY,
    RESERVATION_CANCELLED,
    RESERVATION_EXPIRED,

    LOAN_CREATED,
    LOAN_DUE_SOON,
    LOAN_OVERDUE,
    LOAN_RETURNED,

    FINE_CREATED,
    FINE_PAID,
    FINE_CANCELLED,

    SYSTEM_MESSAGE
}
